"""add timestamp row in comments

Revision ID: 032040ea67a1
Revises: f2cc6f5d7d35
Create Date: 2022-02-17 22:02:45.731167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032040ea67a1'
down_revision = 'f2cc6f5d7d35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('timestamp', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'timestamp')
    # ### end Alembic commands ###
