"""empty message

Revision ID: 553feae0b6d9
Revises: 8df5cfbd4cdf
Create Date: 2022-03-17 12:23:15.278651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553feae0b6d9'
down_revision = '8df5cfbd4cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'song_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'song_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
