"""empty message

Revision ID: f2cc6f5d7d35
Revises: 58d815af6ee6
Create Date: 2022-02-17 12:36:20.677610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2cc6f5d7d35'
down_revision = '58d815af6ee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'image_url')
    # ### end Alembic commands ###
